# Example config for experiment
errors:
  - type: missing_values
    column: 'review/appearance'
    fraction: 0.01
    missingness: 'MAR'
  - type: missing_values
    column: 'review/aroma'
    fraction: 0.01
    missingness: 'MAR'
  # - type: missing_values
  #   column: 'review/palate'
  #   fraction: 0.1
  #   missingness: 'MAR'
  # - type: missing_values
  #   column: 'review/taste'
  #   fraction: 0.1
  #   missingness: 'MAR'
  
  - type: scaling
    column: 'review/palate'
    fraction: 0.01
    sampling: 'MAR'
  - type: scaling
    column: 'review/taste'
    fraction: 0.01
    sampling: 'MAR'

  - type: typo
    column: 'review/text'
    typo_rate: 0.001
    
  # - type: gibberish
  #   column: 'review/text'
  #   gibberish_rate: 0.02

# review/appearance,review/aroma,review/palate,review/taste